name: build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"
      - LICENSE
      - .github/FUNDING.yml
    branches: [main, dev]
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
      - .github/FUNDING.yml
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: "pip" # caching pip dependencies

      - name: Installing pip dependencies
        run: pip install --upgrade pip clickgen
        continue-on-error: false

      # https://github.com/returntocorp/semgrep/issues/4794
      - name: Fixing 'attr' module error
        run: pip install --force-reinstall --upgrade attrs

      - name: Building `Bibata Modern Amber` Cursors
        run: ctgen build.toml -n 'Bibata-Modern-Amber' -c 'Yellowish and rounded edge Bibata cursors.' -d 'bitmaps/Bibata-Modern-Amber'

      - name: Building `Bibata Original Amber` Cursors
        run: ctgen build.toml -n 'Bibata-Original-Amber' -c 'Yellowish and sharp edge Bibata cursors.' -d 'bitmaps/Bibata-Original-Amber'

      - name: Building `Bibata Modern Classic` Cursors
        run: ctgen build.toml -n 'Bibata-Modern-Classic' -c 'Black and rounded edge Bibata cursors.' -d 'bitmaps/Bibata-Modern-Classic'

      - name: Building `Bibata Original Classic` Cursors
        run: ctgen build.toml -n 'Bibata-Original-Classic' -c 'Black and sharp edge Bibata cursors.' -d 'bitmaps/Bibata-Original-Classic'

      - name: Building `Bibata Modern Ice` Cursors
        run: ctgen build.toml -n 'Bibata-Modern-Ice' -c 'White and rounded edge Bibata cursors.' -d 'bitmaps/Bibata-Modern-Ice'

      - name: Building `Bibata Original Ice` Cursors
        run: ctgen build.toml -n 'Bibata-Original-Ice' -c 'White and sharp edge bibata cursors.' -d 'bitmaps/Bibata-Original-Ice'
